# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Create new Release Draft
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          tag_prefix: 'v'
          default_bump: false

      - name: Set Configurations
        if: steps.tag_version.outputs.release_type
        shell: bash
        env:
          OLD_VERSION: ${{ steps.tag_version.outputs.previous_version }}
          VERSION: ${{ steps.tag_version.outputs.new_version }}
        run: sed -ri 's/(__version__ = ")([0-9]+\.[0-9]+\.[0-9]+?.*)(")/\1'"$VERSION"'\3/' "src/gpt_review/__init__.py" || exit 1

      - uses: EndBug/add-and-commit@v9
        if: steps.tag_version.outputs.release_type
        with:
          message: Update Version to ${{ steps.tag_version.outputs.new_version }} [no ci]
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: "src/gpt_review/__init__.py"

      - if: steps.tag_version.outputs.release_type
        run: |
          python -m pip install --upgrade pip
          python -m pip install flit

          python -m flit build

      - if: steps.tag_version.outputs.release_type
        run: |
          gh release delete $TAG || echo "no tag existed"

          gh release create \
            -d \
            --target main \
            --generate-notes \
            $TAG \
            LICENSE dist/*.tar.gz dist/*.whl
        env:
          TAG: ${{ steps.tag_version.outputs.new_tag }}
          GH_TOKEN: ${{ secrets.PAT }}
