# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Create new release
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          default_bump: false

      - name: Set Configurations
        if: steps.tag_version.outputs.release_type
        shell: bash
        env:
          OLD_VERSION: ${{ steps.tag_version.outputs.previous_version }}
          VERSION: ${{ steps.tag_version.outputs.new_version }}
        run: sed -ri 's/(__version__ = ")([0-9]+\.[0-9]+\.[0-9]+?.*)(")/\1'"$VERSION"'\3/' "src/gpt_review/__init__.py" || exit 1

      - uses: EndBug/add-and-commit@v9
        if: steps.tag_version.outputs.release_type
        with:
          message: Update Version to ${{ steps.tag_version.outputs.new_version }} [no ci]
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: "src/gpt_review/__init__.py"

      - name: Remove old release draft 
        if: steps.tag_version.outputs.release_type
        shell: bash
        run: hub release delete latest || exit 0

      - uses: dciborow/action-github-releases@v1.0.1
        if: steps.tag_version.outputs.release_type
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: true
          title: ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true
          prerelease: false
          files: |
            LICENSE.md
            dist/*.tar.gz
            dist/*.whl
